// <auto-generated />
using System;
using CarRentalSystem.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalSystem.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    [Migration("20260115160232_PaymentFixV2")]
    partial class PaymentFixV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalSystem.Entities.Maintenance.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Company = "PZU",
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "PZU-001",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Company = "Allianz",
                            EndDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "ALL-002",
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Company = "Warta",
                            EndDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "WRT-003",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            Company = "PZU",
                            EndDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "PZU-004",
                            StartDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            Company = "Allianz",
                            EndDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "ALL-005",
                            StartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            Company = "Warta",
                            EndDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "WRT-006",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            Company = "PZU",
                            EndDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "PZU-007",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            Company = "Allianz",
                            EndDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "ALL-008",
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            Company = "Warta",
                            EndDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "WRT-009",
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            Company = "PZU",
                            EndDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "PZU-010",
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Maintenance.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceCenterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ServiceCenterId");

                    b.ToTable("Repairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Cost = 150m,
                            Description = "Wymiana oleju",
                            RepairDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Cost = 350m,
                            Description = "Naprawa hamulców",
                            RepairDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Cost = 220m,
                            Description = "Wymiana filtrów",
                            RepairDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 3
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            Cost = 450m,
                            Description = "Naprawa zawieszenia",
                            RepairDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 4
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            Cost = 180m,
                            Description = "Wymiana klocków hamulcowych",
                            RepairDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 5
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            Cost = 600m,
                            Description = "Naprawa skrzyni biegów",
                            RepairDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 6
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            Cost = 200m,
                            Description = "Wymiana amortyzatorów",
                            RepairDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 7
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            Cost = 280m,
                            Description = "Przegląd okresowy",
                            RepairDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 8
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            Cost = 320m,
                            Description = "Naprawa układu wydechowego",
                            RepairDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 9
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            Cost = 400m,
                            Description = "Wymiana akumulatora",
                            RepairDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceCenterId = 10
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Maintenance.ServiceCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PartnershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCenters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            Email = "kontakt@warszawa-serwis.pl",
                            Name = "Auto Serwis Warszawa",
                            PartnershipStartDate = new DateTime(2015, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "600111222"
                        },
                        new
                        {
                            Id = 2,
                            City = "Kraków",
                            Email = "biuro@mechanikakrakow.pl",
                            Name = "Mechanika Kraków",
                            PartnershipStartDate = new DateTime(2016, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "601222333"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gdańsk",
                            Email = "kontakt@serwisgdansk.pl",
                            Name = "Serwis Gdańsk",
                            PartnershipStartDate = new DateTime(2017, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "602333444"
                        },
                        new
                        {
                            Id = 4,
                            City = "Poznań",
                            Email = "biuro@autonaprawapoznan.pl",
                            Name = "AutoNaprawa Poznań",
                            PartnershipStartDate = new DateTime(2018, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "603444555"
                        },
                        new
                        {
                            Id = 5,
                            City = "Łódź",
                            Email = "kontakt@warsztatlodz.pl",
                            Name = "Warsztat Łódź",
                            PartnershipStartDate = new DateTime(2016, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "604555666"
                        },
                        new
                        {
                            Id = 6,
                            City = "Wrocław",
                            Email = "biuro@wroclaw-serwis.pl",
                            Name = "Auto Serwis Wrocław",
                            PartnershipStartDate = new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "605666777"
                        },
                        new
                        {
                            Id = 7,
                            City = "Szczecin",
                            Email = "kontakt@mechanikaszczecin.pl",
                            Name = "Mechanika Szczecin",
                            PartnershipStartDate = new DateTime(2015, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "606777888"
                        },
                        new
                        {
                            Id = 8,
                            City = "Bydgoszcz",
                            Email = "biuro@serwisbydgoszcz.pl",
                            Name = "Serwis Bydgoszcz",
                            PartnershipStartDate = new DateTime(2016, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "607888999"
                        },
                        new
                        {
                            Id = 9,
                            City = "Lublin",
                            Email = "kontakt@warsztatlublin.pl",
                            Name = "Warsztat Lublin",
                            PartnershipStartDate = new DateTime(2017, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "608999000"
                        },
                        new
                        {
                            Id = 10,
                            City = "Katowice",
                            Email = "biuro@autonaprawakatowice.pl",
                            Name = "AutoNaprawa Katowice",
                            PartnershipStartDate = new DateTime(2018, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "609000111"
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Rentals.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount_Positive", "[Amount] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 250m,
                            PaymentDate = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            RentalId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 390m,
                            PaymentDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            RentalId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 600m,
                            PaymentDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "BankTransfer",
                            RentalId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 475m,
                            PaymentDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "BLIK",
                            RentalId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 225m,
                            PaymentDate = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            RentalId = 5,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 450m,
                            PaymentDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            RentalId = 6,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 425m,
                            PaymentDate = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "BankTransfer",
                            RentalId = 7,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 275m,
                            PaymentDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "BLIK",
                            RentalId = 8,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 420m,
                            PaymentDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            RentalId = 9,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 400m,
                            PaymentDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            RentalId = 10,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Rentals.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Rentals", t =>
                        {
                            t.HasCheckConstraint("CK_Rental_Dates", "[ReturnDate] IS NULL OR [ReturnDate] >= [RentalDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            EmployeeId = 1,
                            RentalDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            ClientId = 2,
                            EmployeeId = 2,
                            RentalDate = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            ClientId = 3,
                            EmployeeId = 3,
                            RentalDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            ClientId = 4,
                            EmployeeId = 4,
                            RentalDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            ClientId = 5,
                            EmployeeId = 5,
                            RentalDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            ClientId = 6,
                            EmployeeId = 6,
                            RentalDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            ClientId = 7,
                            EmployeeId = 7,
                            RentalDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            ClientId = 8,
                            EmployeeId = 8,
                            RentalDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            ClientId = 9,
                            EmployeeId = 9,
                            RentalDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            ClientId = 10,
                            EmployeeId = 10,
                            RentalDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Users.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            Email = "jan.kowalski@example.com",
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PESEL = "88010112345",
                            PhoneNumber = "600123456",
                            PostalCode = "00-001"
                        },
                        new
                        {
                            Id = 2,
                            City = "Kraków",
                            Email = "anna.nowak@example.com",
                            FirstName = "Anna",
                            LastName = "Nowak",
                            PESEL = "90020223456",
                            PhoneNumber = "601234567",
                            PostalCode = "30-002"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gdańsk",
                            Email = "piotr.wisniewski@example.com",
                            FirstName = "Piotr",
                            LastName = "Wiśniewski",
                            PESEL = "85030334567",
                            PhoneNumber = "602345678",
                            PostalCode = "80-003"
                        },
                        new
                        {
                            Id = 4,
                            City = "Poznań",
                            Email = "katarzyna.wojcik@example.com",
                            FirstName = "Katarzyna",
                            LastName = "Wójcik",
                            PESEL = "92040445678",
                            PhoneNumber = "603456789",
                            PostalCode = "60-004"
                        },
                        new
                        {
                            Id = 5,
                            City = "Łódź",
                            Email = "michal.krawczyk@example.com",
                            FirstName = "Michał",
                            LastName = "Krawczyk",
                            PESEL = "87050556789",
                            PhoneNumber = "604567890",
                            PostalCode = "90-005"
                        },
                        new
                        {
                            Id = 6,
                            City = "Wrocław",
                            Email = "agnieszka.kaminska@example.com",
                            FirstName = "Agnieszka",
                            LastName = "Kamińska",
                            PESEL = "91060667890",
                            PhoneNumber = "605678901",
                            PostalCode = "50-006"
                        },
                        new
                        {
                            Id = 7,
                            City = "Szczecin",
                            Email = "tomasz.lewandowski@example.com",
                            FirstName = "Tomasz",
                            LastName = "Lewandowski",
                            PESEL = "86070778901",
                            PhoneNumber = "606789012",
                            PostalCode = "70-007"
                        },
                        new
                        {
                            Id = 8,
                            City = "Bydgoszcz",
                            Email = "magdalena.zielinska@example.com",
                            FirstName = "Magdalena",
                            LastName = "Zielińska",
                            PESEL = "93080889012",
                            PhoneNumber = "607890123",
                            PostalCode = "85-008"
                        },
                        new
                        {
                            Id = 9,
                            City = "Lublin",
                            Email = "lukasz.szymanski@example.com",
                            FirstName = "Łukasz",
                            LastName = "Szymański",
                            PESEL = "88090990123",
                            PhoneNumber = "608901234",
                            PostalCode = "20-009"
                        },
                        new
                        {
                            Id = 10,
                            City = "Katowice",
                            Email = "ewa.dabrowska@example.com",
                            FirstName = "Ewa",
                            LastName = "Dąbrowska",
                            PESEL = "90010101234",
                            PhoneNumber = "609012345",
                            PostalCode = "40-010"
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Users.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_Employee_Salary_Positive", "[Salary] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Piotr",
                            HireDate = new DateTime(2018, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nowak",
                            Phone = "600111222",
                            Position = "Kierownik",
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Anna",
                            HireDate = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kowalska",
                            Phone = "601222333",
                            Position = "Kasjer",
                            Salary = 4200m
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Michał",
                            HireDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wiśniewski",
                            Phone = "602333444",
                            Position = "Specjalista ds. Wynajmu",
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Katarzyna",
                            HireDate = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wójcik",
                            Phone = "603444555",
                            Position = "Asystent",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Tomasz",
                            HireDate = new DateTime(2017, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kamiński",
                            Phone = "604555666",
                            Position = "Mechanik",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Magdalena",
                            HireDate = new DateTime(2019, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lewandowska",
                            Phone = "605666777",
                            Position = "Specjalista ds. Klientów",
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Łukasz",
                            HireDate = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Zieliński",
                            Phone = "606777888",
                            Position = "Kierownik ds. Floty",
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Ewa",
                            HireDate = new DateTime(2020, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Szymańska",
                            Phone = "607888999",
                            Position = "Asystent",
                            Salary = 4100m
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Paweł",
                            HireDate = new DateTime(2021, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Dąbrowski",
                            Phone = "608999000",
                            Position = "Specjalista ds. Wynajmu",
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Agnieszka",
                            HireDate = new DateTime(2019, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kowalczyk",
                            Phone = "609000111",
                            Position = "Kasjer",
                            Salary = 4300m
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands", t =>
                        {
                            t.HasCheckConstraint("CK_Brand_Year_Range", "[Year] >= 2000 AND [Year] <= 2025");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Sedan",
                            BrandName = "Toyota",
                            Country = "Japan",
                            Transmission = "Automatic",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "SUV",
                            BrandName = "BMW",
                            Country = "Germany",
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "Hatchback",
                            BrandName = "Ford",
                            Country = "USA",
                            Transmission = "Manual",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            BodyType = "Coupe",
                            BrandName = "Audi",
                            Country = "Germany",
                            Transmission = "Automatic",
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            BodyType = "Sedan",
                            BrandName = "Volkswagen",
                            Country = "Germany",
                            Transmission = "Manual",
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            BodyType = "SUV",
                            BrandName = "Honda",
                            Country = "Japan",
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            BodyType = "Sedan",
                            BrandName = "Mercedes-Benz",
                            Country = "Germany",
                            Transmission = "Automatic",
                            Year = 2024
                        },
                        new
                        {
                            Id = 8,
                            BodyType = "Hatchback",
                            BrandName = "Kia",
                            Country = "South Korea",
                            Transmission = "Manual",
                            Year = 2023
                        },
                        new
                        {
                            Id = 9,
                            BodyType = "SUV",
                            BrandName = "Nissan",
                            Country = "Japan",
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            BodyType = "Coupe",
                            BrandName = "Chevrolet",
                            Country = "USA",
                            Transmission = "Manual",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Cars", t =>
                        {
                            t.HasCheckConstraint("CK_Car_Mileage_Positive", "[Mileage] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailabilityStatus = "Available",
                            DailyPrice = 50m,
                            Location = "Warszawa",
                            Mileage = 15000,
                            ModelId = 1,
                            RegistrationNumber = "WA12345"
                        },
                        new
                        {
                            Id = 2,
                            AvailabilityStatus = "Available",
                            DailyPrice = 65m,
                            Location = "Warszawa",
                            Mileage = 22000,
                            ModelId = 2,
                            RegistrationNumber = "WA23456"
                        },
                        new
                        {
                            Id = 3,
                            AvailabilityStatus = "Maintenance",
                            DailyPrice = 120m,
                            Location = "Kraków",
                            Mileage = 30000,
                            ModelId = 3,
                            RegistrationNumber = "KR34567"
                        },
                        new
                        {
                            Id = 4,
                            AvailabilityStatus = "Rented",
                            DailyPrice = 95m,
                            Location = "Kraków",
                            Mileage = 18000,
                            ModelId = 4,
                            RegistrationNumber = "KR45678"
                        },
                        new
                        {
                            Id = 5,
                            AvailabilityStatus = "Available",
                            DailyPrice = 45m,
                            Location = "Gdańsk",
                            Mileage = 12000,
                            ModelId = 5,
                            RegistrationNumber = "GD56789"
                        },
                        new
                        {
                            Id = 6,
                            AvailabilityStatus = "Reserved",
                            DailyPrice = 75m,
                            Location = "Gdańsk",
                            Mileage = 25000,
                            ModelId = 6,
                            RegistrationNumber = "GD67890"
                        },
                        new
                        {
                            Id = 7,
                            AvailabilityStatus = "Available",
                            DailyPrice = 85m,
                            Location = "Poznań",
                            Mileage = 20000,
                            ModelId = 7,
                            RegistrationNumber = "PO78901"
                        },
                        new
                        {
                            Id = 8,
                            AvailabilityStatus = "Available",
                            DailyPrice = 55m,
                            Location = "Łódź",
                            Mileage = 15000,
                            ModelId = 8,
                            RegistrationNumber = "LO89012"
                        },
                        new
                        {
                            Id = 9,
                            AvailabilityStatus = "Rented",
                            DailyPrice = 70m,
                            Location = "Wrocław",
                            Mileage = 18000,
                            ModelId = 9,
                            RegistrationNumber = "WR90123"
                        },
                        new
                        {
                            Id = 10,
                            AvailabilityStatus = "Available",
                            DailyPrice = 80m,
                            Location = "Szczecin",
                            Mileage = 16000,
                            ModelId = 10,
                            RegistrationNumber = "SZ01234"
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ModelName = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            ModelName = "Camry"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            ModelName = "X5"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            ModelName = "3 Series"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            ModelName = "Focus"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            ModelName = "Mustang"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            ModelName = "A5"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 5,
                            ModelName = "Passat"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 6,
                            ModelName = "CR-V"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 7,
                            ModelName = "C-Class"
                        });
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Maintenance.Insurance", b =>
                {
                    b.HasOne("CarRentalSystem.Entities.Vehicles.Car", "Car")
                        .WithOne("Insurance")
                        .HasForeignKey("CarRentalSystem.Entities.Maintenance.Insurance", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Maintenance.Repair", b =>
                {
                    b.HasOne("CarRentalSystem.Entities.Vehicles.Car", "Car")
                        .WithMany("Repairs")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalSystem.Entities.Maintenance.ServiceCenter", "ServiceCenter")
                        .WithMany("Repairs")
                        .HasForeignKey("ServiceCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("ServiceCenter");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Rentals.Payment", b =>
                {
                    b.HasOne("CarRentalSystem.Entities.Rentals.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Rentals.Rental", b =>
                {
                    b.HasOne("CarRentalSystem.Entities.Vehicles.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalSystem.Entities.Users.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalSystem.Entities.Users.Employee", "Employee")
                        .WithMany("Rentals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Car", b =>
                {
                    b.HasOne("CarRentalSystem.Entities.Vehicles.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Model", b =>
                {
                    b.HasOne("CarRentalSystem.Entities.Vehicles.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Maintenance.ServiceCenter", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Rentals.Rental", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Users.Client", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Users.Employee", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("CarRentalSystem.Entities.Vehicles.Car", b =>
                {
                    b.Navigation("Insurance");

                    b.Navigation("Rentals");

                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
